#!/usr/bin/env python
# File generated by reverse AIRIUM translator (version 0.2.3).
# Any change will be overridden on next run.
# flake8: noqa E501 (line too long)

from airium import Airium

a = Airium()

a('<!DOCTYPE <!doctype html>')
with a.html(xmlns='http://www.w3.org/1999/xhtml', **{'xmlns:o': 'urn:schemas-microsoft-com:office:office',
 'xmlns:v': 'urn:schemas-microsoft-com:vml'}):
    with a.head():
        a.title(_t="soc-announce")
        a.meta(content='IE=edge', **{'http-equiv': 'X-UA-Compatible'})
        a.meta(content='text/html; charset=UTF-8', **{'http-equiv': 'Content-Type'})
        a.meta(content='width=device-width, initial-scale=1', name='viewport')
        a.link(href='https://fonts.googleapis.com/css?family=Ubuntu:300,400,500,700', rel='stylesheet', type='text/css')
        with a.style(type='text/css'):
            a('#outlook a {padding: 0;}.ReadMsgBody {width: 100%;}.ExternalClass {width: 100%;}.ExternalClass * {line-height: 100%;}body {margin: 0;padding: 0;-webkit-text-size-adjust: 100%;-ms-text-size-adjust: 100%;}table,td {border-collapse: collapse;mso-table-lspace: 0pt;mso-table-rspace: 0pt;}img {border: 0;height: auto;line-height: 100%;outline: none;text-decoration: none;-ms-interpolation-mode: bicubic;}p {display: block;margin: 13px 0;}a {text-decoration:none;color: white;}')
        with a.style(type='text/css'):
            a('@media only screen and (max-width:480px) {@-ms-viewport {width: 320px;}@viewport {width: 320px;}}')
        with a.style(type='text/css'):
            a('@import url(https://fonts.googleapis.com/css?family=Ubuntu:300,400,500,700);')
        with a.style(type='text/css'):
            a('@media only screen and (min-width:480px) {.mj-column-px-600 {width: 600px!important;max-width: 600px;}.mj-column-px-500 {width: 500px!important;max-width: 500px;}.mj-column-per-50 {width: 50%!important;max-width: 50%;}.mj-column-per-100 {width: 100%!important;max-width: 100%;}}')
        with a.style(type='text/css'):
            a('@media only screen and (max-width:480px) {table.full-width-mobile {width: 100%!important;}td.full-width-mobile {width: auto!important;}}')
        with a.style(type='text/css'):
            a('@media only screen and (max-width:480px) {.height-fix {height:80px!important;}}')
        with a.style(type='text/css'):
            a('@media only screen and (max-width:480px) {.height-fix-sponsor {height:185px!important;}}')
    with a.body(style='background-color:#ffffff;'):
        with a.table(align='center', border='0', cellpadding='0', cellspacing='0', role='presentation', style='background-color:#f0f0f0;width:800px;margin:auto;'):
            with a.tbody():
                with a.tr():
                    with a.td():
                        a('<!-- START Top Space ----------------->')
                        with a.div(style='background:#f0f0f0;background-color:#f0f0f0;Margin:0px auto;max-width:600px;'):
                            with a.table(align='center', border='0', cellpadding='0', cellspacing='0', role='presentation', style='background:#f0f0f0;background-color:#f0f0f0;width:100%;'):
                                with a.tbody():
                                    with a.tr():
                                        a.td(style='direction:ltr;font-size:0px;padding:20px 0;text-align:center;vertical-align:top;')
                        a('<!-- END Top Space -------------------->')
                        a('<!-- START CSESoc Logo Header --------->')
                        with a.div(klass='height-fix', style='background:url(https://imgur.com/eQfBCYl.jpg) bottom center / contain no-repeat;Margin:0px auto;max-width:600px;height:130px;'):
                            with a.div(style='line-height:0;font-size:0;'):
                                with a.table(align='center', border='0', cellpadding='0', cellspacing='0', role='presentation', **{'width:"100%"': ''}):
                                    with a.tbody():
                                        with a.tr():
                                            a.td(style='direction:ltr;font-size:0px;padding:20px 0;text-align:center;vertical-align:top;')
                        a('<!-- END Image Title Section --------->')
                        a('<!-- xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  Start Divider to upcoming events xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx-->')
                        with a.div(style='background:#ffffff;background-color:#ffffff;Margin:0px auto;max-width:600px;'):
                            with a.table(align='center', border='0', cellpadding='0', cellspacing='0', role='presentation', style='background:#ffffff;background-color:#ffffff;width:100%;'):
                                with a.tbody():
                                    with a.tr():
                                        with a.td(style='direction:ltr;font-size:0px;padding:5px 0;text-align:center;vertical-align:top;'):
                                            a.p(style='border-top:dashed 1px lightgrey;font-size:1;margin:0px auto;width:100%;padding-bottom:15px;')
                                            with a.div(klass='mj-column-per-50 outlook-group-fix', style='font-size:13px;text-align:left;direction:ltr;display:inline-block;vertical-align:top;width:50%;'):
                                                a.table(border='0', cellpadding='0', cellspacing='0', role='presentation', style='vertical-align:top;', width='100%')
                        a('<!-- xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx   END divider to upcoming events  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx-->')
                        a('<!-- START Intro / Upcoming Events --------->')
                        with a.div(style='background:#ffffff;background-color:#ffffff;Margin:0px auto;max-width:600px;'):
                            with a.table(align='center', border='0', cellpadding='0', cellspacing='0', role='presentation', style='background:#ffffff;background-color:#ffffff;width:100%;'):
                                with a.tbody():
                                    with a.tr():
                                        with a.td(style='direction:ltr;font-size:0px;padding:20px 0;text-align:center;vertical-align:top;'):
                                            with a.div(klass='mj-column-px-500 outlook-group-fix', style='font-size:13px;text-align:left;direction:ltr;display:inline-block;vertical-align:top;width:100%;'):
                                                with a.table(border='0', cellpadding='0', cellspacing='0', role='presentation', style='vertical-align:top;', width='100%'):
                                                    with a.tr():
                                                        with a.td(align='center', style='font-size:0px;padding:10px 25px;word-break:break-word;'):
                                                            with a.div(style='font-family:Helvetica;font-size:20px;font-weight:bold;line-height:1;text-align:center;color:#000000;'):
                                                                a('UPCOMING EVENTS')
                                                    with a.tr():
                                                        with a.td(align='center', style='font-size:0px;padding:0px 0px;word-break:break-word;'):
                                                            with a.div(style='font-family:Ubuntu, Helvetica, Arial, sans-serif;font-size:25px;font-weight: bold;line-height:1;text-align:center;color:#1051ea;'):
                                                                a('___')
                        a('<!-- END Intro / Upcoming Events --------->')
                        a('<!-- xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  START Event xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx-->')
                        with a.div(style='background:#ffffff;background-color:#ffffff;Margin:0px auto;max-width:600px;'):
                            with a.table(align='center', border='0', cellpadding='0', cellspacing='0', role='presentation', style='background:#ffffff;background-color:#ffffff;width:100%;'):
                                with a.tbody():
                                    with a.tr():
                                        with a.td(style='direction:ltr;font-size:0px;padding:5px 0;text-align:center;vertical-align:top;'):
                                            a.p(style='border-top:dashed 1px lightgrey;font-size:1;margin:0px auto;width:100%;padding-bottom:15px;')
                                            with a.div(klass='mj-column-per-50 outlook-group-fix', style='font-size:13px;text-align:left;direction:ltr;display:inline-block;vertical-align:top;width:50%;'):
                                                with a.table(border='0', cellpadding='0', cellspacing='0', role='presentation', style='vertical-align:top;', width='100%'):
                                                    with a.tr():
                                                        with a.td(align='left', style='font-size:0px;padding:10px;word-break:break-word;'):
                                                            with a.table(align='left', border='0', cellpadding='0', cellspacing='0', role='presentation', style='border-collapse:collapse;border-spacing:0px;'):
                                                                with a.tbody():
                                                                    with a.tr():
                                                                        a('<!-- EVENT IMAGE -->')
                                                                        with a.td(style='width:280px;'):
                                                                            a.img(height='auto', src='https://scontent.fsyd11-1.fna.fbcdn.net/v/t39.30808-6/p180x540/269600549_5177815778918019_3850127099860235996_n.jpg?_nc_cat=104&ccb=1-5&_nc_sid=340051&_nc_ohc=fbUOTNWsN68AX8mefrS&_nc_ht=scontent.fsyd11-1.fna&oh=00_AT_Wp4HGCVJFOKrCZGHjCNII9gsVIMhf6Ulbe1vozG-TRg&oe=61DACE75', style='border:0;display:inline-block;outline:none;text-decoration:none;height:auto;width:100%;', width='280')
                                            a('<!-- right paragraph -->')
                                            with a.div(klass='mj-column-per-50 outlook-group-fix', style='font-size:13px;text-align:left;direction:ltr;display:inline-block;vertical-align:top;width:50%;'):
                                                with a.table(border='0', cellpadding='0', cellspacing='0', role='presentation', style='vertical-align:top;', width='100%'):
                                                    with a.tr():
                                                        with a.td(align='left', style='font-size:0px;padding:9px 25px;word-break:break-word;'):
                                                            a('<!-- EVENT TITLE -->')
                                                            with a.div(style='font-family:Helvetica;font-size:17px;font-weight:bold;line-height:1;text-align:left;color:black;'):
                                                                a('CSESoc 2022 Peer Mentor Recruitment')
                                                    with a.tr():
                                                        with a.td(align='left', style='font-size:0px;padding:9px 25px;word-break:break-word;'):
                                                            a('<!-- EVENT DESCRIPTION -->')
                                                            with a.div(style='font-family:Ubuntu, Helvetica, Arial, sans-serif;font-size:13px;line-height:1;text-align:left;color:#525252;'):
                                                                a('Helping the future of CSE one student at a time. 🤩')
                                                                a.br()
                                                                a.br()
                                                                a('✨ APPLY HERE ✨')
                                                                a.br()
                                                                a.br()
                                                                with a.a(href='http://bit.ly/CSESocPeerMentorApplication2022', style='color:blue;', target='_blank'):
                                                                    a('http://bit.ly/CSESocPeerMentorApplication2022')
                                                                a.br()
                                                                a.br()
                                                                a('Registrations close 11:59 pm on Friday, 14th January 2022!! GET IN QUICK! Applications will be reviewed on a ROLLING BASIS.')
                                                                a.br()
                                                                a.br()
                                                                a('Note: Returning peer mentors need to apply but do not require an interview; only new peer mentors will be interviewed.')
                                                                a.br()
                                                                a.br()
                                                                a('✨ DETAILS ✨')
                                                                a.br()
                                                                a.br()
                                                                a('Peer mentors are an important part of CSESoc and university life at UNSW. We are looking for enthusiastic students who are passionate about helping first-year students, gaining leadership experience, communication skills, some resume-worthy additions, and having a lot of fun in the upcoming term (Term 1, 2022)! 🎉')
                                                                a.br()
                                                                a.br()
                                                                a("CSESoc's peer mentoring is one of the biggest peer mentoring programs in the uni, with 400 mentees and 100 mentors in 2021! 😱 This program allows us to have a huge impact on first-year students, and give them the boost that they need to succeed.")
                                                                a.br()
                                                                a.br()
                                                                a('Mentors can choose to sign-up (doing separate forms but noting preferences) as pairs OR as an individual (where we will buddy you up with a new friend!). The two of you will receive your very own little squad of first-years to guide through their transition to uni. We will have heaps of fun events throughout the term and lots of opportunities to meet new people. 🤗')
                                                                a.br()
                                                                a.br()
                                                                a('✨ CONTACT ✨')
                                                                a.br()
                                                                a.br()
                                                                a('Contact: Timmy Huang and Priscilla Soo (CSESoc Student Experience Directors)')
                                                                a.br()
                                                                a.br()
                                                                a('Email: studex@csesoc.org.au')
                                                                a.br()
                                                                a.br()
                                                                a('Peer Mentoring @ UNSW website:')
                                                                with a.a(href='https://www.student.unsw.edu.au/peersupport', style='color:blue;', target='_blank'):
                                                                    a('https://www.student.unsw.edu.au/peersupport')
                                                    with a.tr():
                                                        with a.td(align='left', style='font-size:0px;padding:9px 25px;word-break:break-word;'):
                                                            a('<!-- EVENT DATE + TIME -->')
                                                            with a.div(style='font-family:Ubuntu, Helvetica, Arial, sans-serif;font-size:13px;font-weight:bold;line-height:1;text-align:left;color:#000000;'):
                                                                a('Registrations close 11:59pm Friday 14 Jan 2022')
                                                    with a.tr():
                                                        with a.td(align='center', style='font-size:0px;padding:10px 25px;word-break:break-word;', **{'vertical-align': 'middle'}):
                                                            with a.table(align='center', border='0', cellpadding='0', cellspacing='0', role='presentation', style='border-collapse:separate;width:100%;line-height:100%;'):
                                                                with a.tr():
                                                                    with a.td(align='center', bgcolor='#1051ea', role='presentation', style='border:none;border-radius:3px;cursor:auto;padding:4px 25px;background:#1051ea;color:#ffffff;font-family:Ubuntu, Helvetica, Arial, sans-serif;font-size:13px;font-weight:normal;Margin:0;text-decoration:none;text-transform:none;', valign='middle'):
                                                                        a('<!-- EVENT LINK -->')
                                                                        with a.a(href='https://www.facebook.com/events/299362098871098', style='text-decoration:none;', target='_blank'):
                                                                            with a.p(style='background:#1051ea;color:#ffffff;font-family:Ubuntu, Helvetica, Arial, sans-serif;font-size:13px;font-weight:normal;line-height:200%;Margin:0;text-decoration:none;text-transform:none;', target='_blank'):
                                                                                a('<!-- EVENT BUTTON TEXT -->')
                                                                                a('SEE MORE')
                        a('<!-- xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx   END EVENT  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx-->')
                        a('<!-- xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  START Event xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx-->')
                        with a.div(style='background:#ffffff;background-color:#ffffff;Margin:0px auto;max-width:600px;'):
                            with a.table(align='center', border='0', cellpadding='0', cellspacing='0', role='presentation', style='background:#ffffff;background-color:#ffffff;width:100%;'):
                                with a.tbody():
                                    with a.tr():
                                        with a.td(style='direction:ltr;font-size:0px;padding:5px 0;text-align:center;vertical-align:top;'):
                                            a.p(style='border-top:dashed 1px lightgrey;font-size:1;margin:0px auto;width:100%;padding-bottom:15px;')
                                            with a.div(klass='mj-column-per-50 outlook-group-fix', style='font-size:13px;text-align:left;direction:ltr;display:inline-block;vertical-align:top;width:50%;'):
                                                with a.table(border='0', cellpadding='0', cellspacing='0', role='presentation', style='vertical-align:top;', width='100%'):
                                                    with a.tr():
                                                        with a.td(align='left', style='font-size:0px;padding:10px;word-break:break-word;'):
                                                            with a.table(align='left', border='0', cellpadding='0', cellspacing='0', role='presentation', style='border-collapse:collapse;border-spacing:0px;'):
                                                                with a.tbody():
                                                                    with a.tr():
                                                                        a('<!-- EVENT IMAGE -->')
                                                                        with a.td(style='width:280px;'):
                                                                            a.img(height='auto', src='https://scontent.fsyd11-2.fna.fbcdn.net/v/t39.30808-6/269977910_5165203386845925_5435982950809456294_n.jpg?_nc_cat=108&ccb=1-5&_nc_sid=340051&_nc_ohc=5oVD12mg_98AX_PNlfv&tn=BCkbZmTQ7CMQkVCf&_nc_ht=scontent.fsyd11-2.fna&oh=00_AT_5HI0zu8M_sH-4633Vuop_FuwN6Z5QA1d_oIwQqVZEZA&oe=61DA8C30', style='border:0;display:inline-block;outline:none;text-decoration:none;height:auto;width:100%;', width='280')
                                            with a.div(klass='mj-column-per-50 outlook-group-fix', style='font-size:13px;text-align:left;direction:ltr;display:inline-block;vertical-align:top;width:50%;'):
                                                with a.table(border='0', cellpadding='0', cellspacing='0', role='presentation', style='vertical-align:top;', width='100%'):
                                                    with a.tr():
                                                        with a.td(align='left', style='font-size:0px;padding:9px 25px;word-break:break-word;'):
                                                            a('<!-- EVENT TITLE -->')
                                                            with a.div(style='font-family:Helvetica;font-size:17px;font-weight:bold;line-height:1;text-align:left;color:black;'):
                                                                a('CSESoc Project Team Recruitment 2022')
                                                    with a.tr():
                                                        with a.td(align='left', style='font-size:0px;padding:9px 25px;word-break:break-word;'):
                                                            a('<!-- EVENT DESCRIPTION -->')
                                                            with a.div(style='font-family:Ubuntu, Helvetica, Arial, sans-serif;font-size:13px;line-height:1;text-align:left;color:#525252;'):
                                                                a('CSESoc is looking for passionate ⭐ and personable individuals 🙋 interested in joining a team to work on real-life 🤩 software projects! Joining the ✨Projects subcommittee✨ offers personal and professional growth, with unique opportunities to develop new features 🧑\u200d💻 and deploy applications, all while making friends 🥰 and being part of an amazing network.')
                                                                a.br()
                                                                a.br()
                                                                a('✨ PROJECTS ✨')
                                                                a.br()
                                                                a('🏷️ Notangles: uni timetabling web app')
                                                                a.br()
                                                                a('🏷️ CSESoc Website')
                                                                a.br()
                                                                a('🏷️ CSESoc Discord Bot')
                                                                a.br()
                                                                a('🏷️ Freerooms: find vacant rooms on campus')
                                                                a.br()
                                                                a('🏷️ Circles: degree planner')
                                                                a.br()
                                                                a('🏷️ Structs: interactive algorithms visualiser')
                                                                a.br()
                                                                a('🏷️ CSElectives: course review website')
                                                                a.br()
                                                                a.br()
                                                                a('✨ ELIGIBILITY ✨')
                                                                a.br()
                                                                a('✔️ Completed COMP1511 (or equivalent) prior to applying')
                                                                a.br()
                                                                a('✔️ Able to commit approximately 5 hours each week')
                                                                a.br()
                                                                a.br()
                                                                a('✨ HOW TO APPLY ✨')
                                                                a.br()
                                                                a('1️⃣ Read the project descriptions here:')
                                                                with a.a(href='https://cseso.cc/ProjectsDescription2022', style='color:blue;', target='_blank'):
                                                                    a('https://cseso.cc/ProjectsDescription2022')
                                                                a.br()
                                                                a('2️⃣ Apply here:')
                                                                with a.a(href='https://cseso.cc/ProjectsApplication2022', style='color:blue;', target='_blank'):
                                                                    a('https://cseso.cc/ProjectsApplication2022')
                                                                a.br()
                                                                a('Applications close 11:59pm Sunday 16th January 2022❗')
                                                                a.br()
                                                                a.br()
                                                                a('If you have any questions, feel free to email projects@csesoc.org.au')
                                                    with a.tr():
                                                        with a.td(align='left', style='font-size:0px;padding:9px 25px;word-break:break-word;'):
                                                            a('<!-- EVENT DATE + TIME -->')
                                                            with a.div(style='font-family:Ubuntu, Helvetica, Arial, sans-serif;font-size:13px;font-weight:bold;line-height:1;text-align:left;color:#000000;'):
                                                                a('Registrations close 11:59pm Sunday 16 Jan 2022')
                                                    with a.tr():
                                                        with a.td(align='center', style='font-size:0px;padding:10px 25px;word-break:break-word;', **{'vertical-align': 'middle'}):
                                                            with a.table(align='center', border='0', cellpadding='0', cellspacing='0', role='presentation', style='border-collapse:separate;width:100%;line-height:100%;'):
                                                                with a.tr():
                                                                    with a.td(align='center', bgcolor='#1051ea', role='presentation', style='border:none;border-radius:3px;cursor:auto;padding:4px 25px;background:#1051ea;color:#ffffff;font-family:Ubuntu, Helvetica, Arial, sans-serif;font-size:13px;font-weight:normal;Margin:0;text-decoration:none;text-transform:none;', valign='middle'):
                                                                        a('<!-- EVENT LINK -->')
                                                                        with a.a(href='https://www.facebook.com/events/2429870770476507', style='text-decoration:none;', target='_blank'):
                                                                            with a.p(style='background:#1051ea;color:#ffffff;font-family:Ubuntu, Helvetica, Arial, sans-serif;font-size:13px;font-weight:normal;line-height:200%;Margin:0;text-decoration:none;text-transform:none;', target='_blank'):
                                                                                a('<!-- EVENT BUTTON TEXT -->')
                                                                                a('SEE MORE')
                        a('<!-- xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx   END EVENT  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx-->')
                        a('<!-- xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  START Event xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx-->')
                        with a.div(style='background:#ffffff;background-color:#ffffff;Margin:0px auto;max-width:600px;'):
                            with a.table(align='center', border='0', cellpadding='0', cellspacing='0', role='presentation', style='background:#ffffff;background-color:#ffffff;width:100%;'):
                                with a.tbody():
                                    with a.tr():
                                        with a.td(style='direction:ltr;font-size:0px;padding:5px 0;text-align:center;vertical-align:top;'):
                                            a.p(style='border-top:dashed 1px lightgrey;font-size:1;margin:0px auto;width:100%;padding-bottom:15px;')
                                            with a.div(klass='mj-column-per-50 outlook-group-fix', style='font-size:13px;text-align:left;direction:ltr;display:inline-block;vertical-align:top;width:50%;'):
                                                with a.table(border='0', cellpadding='0', cellspacing='0', role='presentation', style='vertical-align:top;', width='100%'):
                                                    with a.tr():
                                                        with a.td(align='left', style='font-size:0px;padding:10px;word-break:break-word;'):
                                                            with a.table(align='left', border='0', cellpadding='0', cellspacing='0', role='presentation', style='border-collapse:collapse;border-spacing:0px;'):
                                                                with a.tbody():
                                                                    with a.tr():
                                                                        a('<!-- EVENT IMAGE -->')
                                                                        with a.td(style='width:280px;'):
                                                                            a.img(height='auto', src='https://scontent.fsyd11-2.fna.fbcdn.net/v/t39.30808-6/266194071_5083182691714662_7054140190762118316_n.jpg?_nc_cat=100&ccb=1-5&_nc_sid=340051&_nc_ohc=Vo2pXq24PpkAX_vafy_&_nc_ht=scontent.fsyd11-2.fna&oh=00_AT_j4Fa371TBMiI31UKnQpqZu_JSSKYC1YupVazlBDCW4w&oe=61DBC454', style='border:0;display:inline-block;outline:none;text-decoration:none;height:auto;width:100%;', width='280')
                                            with a.div(klass='mj-column-per-50 outlook-group-fix', style='font-size:13px;text-align:left;direction:ltr;display:inline-block;vertical-align:top;width:50%;'):
                                                with a.table(border='0', cellpadding='0', cellspacing='0', role='presentation', style='vertical-align:top;', width='100%'):
                                                    with a.tr():
                                                        with a.td(align='left', style='font-size:0px;padding:9px 25px;word-break:break-word;'):
                                                            a('<!-- EVENT TITLE -->')
                                                            with a.div(style='font-family:Helvetica;font-size:17px;font-weight:bold;line-height:1;text-align:left;color:black;'):
                                                                a('CSESoc First Year Camp Leader Applications 2022')
                                                    with a.tr():
                                                        with a.td(align='left', style='font-size:0px;padding:9px 25px;word-break:break-word;'):
                                                            a('<!-- EVENT DESCRIPTION -->')
                                                            with a.div(style='font-family:Ubuntu, Helvetica, Arial, sans-serif;font-size:13px;line-height:1;text-align:left;color:#525252;'):
                                                                a('CSESoc is hosting its annual First Year Camp 🌟 for 2022 and we’re recruiting camp leaders! If you’re enthusiastic, fun 🤩 and keen to provide first years with an unforgettable experience, apply now!')
                                                                a.br()
                                                                a.br()
                                                                a('✨ DETAILS ✨')
                                                                a.br()
                                                                a('Application period: 15th December 2021 – 10th January 2022')
                                                                a.br()
                                                                a('Where: Online')
                                                                a.br()
                                                                a.br()
                                                                a('✨ ELIGIBILITY ✨')
                                                                a.br()
                                                                a('✅ Keen to lead and provide an amazing experience for first years')
                                                                a.br()
                                                                a('✅ Willing to work and help other camp leaders')
                                                                a.br()
                                                                a('❗ Camp will be run from the 4th to 6th March 2022. There will be an induction day and 2-3 training days, each around 3 hours that will take place in the weeks leading up to camp.')
                                                                a.br()
                                                                a.br()
                                                                a('✨ APPLY HERE ✨')
                                                                a.br()
                                                                with a.a(href='https://forms.gle/VfbD2wXs3KkiJzMw8', style='color:blue;', target='_blank'):
                                                                    a('https://forms.gle/VfbD2wXs3KkiJzMw8')
                                                                a.br()
                                                                a('Note that applications are considered on a rolling basis, so apply as early as possible. If you have any questions about anything, feel free to email socials@csesoc.org.au')
                                                                a.br()
                                                    with a.tr():
                                                        with a.td(align='left', style='font-size:0px;padding:9px 25px;word-break:break-word;'):
                                                            a('<!-- EVENT DATE + TIME -->')
                                                            with a.div(style='font-family:Ubuntu, Helvetica, Arial, sans-serif;font-size:13px;font-weight:bold;line-height:1;text-align:left;color:#000000;'):
                                                                a('Registrations close 10 Jan 2022')
                                                    with a.tr():
                                                        with a.td(align='center', style='font-size:0px;padding:10px 25px;word-break:break-word;', **{'vertical-align': 'middle'}):
                                                            with a.table(align='center', border='0', cellpadding='0', cellspacing='0', role='presentation', style='border-collapse:separate;width:100%;line-height:100%;'):
                                                                with a.tr():
                                                                    with a.td(align='center', bgcolor='#1051ea', role='presentation', style='border:none;border-radius:3px;cursor:auto;padding:4px 25px;background:#1051ea;color:#ffffff;font-family:Ubuntu, Helvetica, Arial, sans-serif;font-size:13px;font-weight:normal;Margin:0;text-decoration:none;text-transform:none;', valign='middle'):
                                                                        a('<!-- EVENT LINK -->')
                                                                        with a.a(href='https://www.facebook.com/events/502096534278601/', style='text-decoration:none;', target='_blank'):
                                                                            with a.p(style='background:#1051ea;color:#ffffff;font-family:Ubuntu, Helvetica, Arial, sans-serif;font-size:13px;font-weight:normal;line-height:200%;Margin:0;text-decoration:none;text-transform:none;', target='_blank'):
                                                                                a('<!-- EVENT BUTTON TEXT -->')
                                                                                a('SEE MORE')
                        a('<!-- xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx   END EVENT  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx-->')
                        a('<!-- xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  Start Divider to external events xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx-->')
                        with a.div(style='background:#ffffff;background-color:#ffffff;Margin:0px auto;max-width:600px;'):
                            with a.table(align='center', border='0', cellpadding='0', cellspacing='0', role='presentation', style='background:#ffffff;background-color:#ffffff;width:100%;'):
                                with a.tbody():
                                    with a.tr():
                                        with a.td(style='direction:ltr;font-size:0px;padding:5px 0;text-align:center;vertical-align:top;'):
                                            a.p(style='border-top:dashed 1px lightgrey;font-size:1;margin:0px auto;width:100%;padding-bottom:15px;')
                                            with a.div(klass='mj-column-per-50 outlook-group-fix', style='font-size:13px;text-align:left;direction:ltr;display:inline-block;vertical-align:top;width:50%;'):
                                                a.table(border='0', cellpadding='0', cellspacing='0', role='presentation', style='vertical-align:top;', width='100%')
                        a('<!-- START Intro / Upcoming Events --------->')
                        with a.div(style='background:#ffffff;background-color:#ffffff;Margin:0px auto;max-width:600px;'):
                            with a.table(align='center', border='0', cellpadding='0', cellspacing='0', role='presentation', style='background:#ffffff;background-color:#ffffff;width:100%;'):
                                with a.tbody():
                                    with a.tr():
                                        with a.td(style='direction:ltr;font-size:0px;padding:20px 0;text-align:center;vertical-align:top;'):
                                            with a.div(klass='mj-column-px-500 outlook-group-fix', style='font-size:13px;text-align:left;direction:ltr;display:inline-block;vertical-align:top;width:100%;'):
                                                with a.table(border='0', cellpadding='0', cellspacing='0', role='presentation', style='vertical-align:top;', width='100%'):
                                                    with a.tr():
                                                        with a.td(align='center', style='font-size:0px;padding:10px 25px;word-break:break-word;'):
                                                            with a.div(style='font-family:Helvetica;font-size:20px;font-weight:bold;line-height:1;text-align:center;color:#000000;'):
                                                                a('MEDIA')
                                                    with a.tr():
                                                        with a.td(align='center', style='font-size:0px;padding:0px 0px;word-break:break-word;'):
                                                            with a.div(style='font-family:Ubuntu, Helvetica, Arial, sans-serif;font-size:25px;font-weight: bold;line-height:1;text-align:center;color:#1051ea;'):
                                                                a('___')
                        a('<!-- END Intro / Upcoming Events --------->')
                        a('<!-- xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  START Event xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx-->')
                        with a.div(style='background:#ffffff;background-color:#ffffff;Margin:0px auto;max-width:600px;'):
                            with a.table(align='center', border='0', cellpadding='0', cellspacing='0', role='presentation', style='background:#ffffff;background-color:#ffffff;width:100%;'):
                                with a.tbody():
                                    with a.tr():
                                        with a.td(style='direction:ltr;font-size:0px;padding:5px 0;text-align:center;vertical-align:top;'):
                                            a.p(style='border-top:dashed 1px lightgrey;font-size:1;margin:0px auto;width:100%;padding-bottom:15px;')
                                            a('<!-- Left image -->')
                                            with a.div(klass='mj-column-per-50 outlook-group-fix', style='font-size:13px;text-align:left;direction:ltr;display:inline-block;vertical-align:top;width:50%;'):
                                                with a.table(border='0', cellpadding='0', cellspacing='0', role='presentation', style='vertical-align:top;', width='100%'):
                                                    with a.tr():
                                                        with a.td(align='left', style='font-size:0px;padding:10px;word-break:break-word;'):
                                                            with a.table(align='left', border='0', cellpadding='0', cellspacing='0', role='presentation', style='border-collapse:collapse;border-spacing:0px;'):
                                                                with a.tbody():
                                                                    with a.tr():
                                                                        a('<!-- EVENT IMAGE -->')
                                                                        with a.td(style='width:280px;'):
                                                                            a.img(height='auto', src='https://media.csesoc.org.au/content/images/size/w2000/2021/12/268181654_592110158538292_8335788803388188583_n.png', style='border:0;display:inline-block;outline:none;text-decoration:none;height:auto;width:100%;', width='280')
                                            a('<!-- right paragraph -->')
                                            with a.div(klass='mj-column-per-50 outlook-group-fix', style='font-size:13px;text-align:left;direction:ltr;display:inline-block;vertical-align:top;width:50%;'):
                                                with a.table(border='0', cellpadding='0', cellspacing='0', role='presentation', style='vertical-align:top;', width='100%'):
                                                    with a.tr():
                                                        with a.td(align='left', style='font-size:0px;padding:9px 25px;word-break:break-word;'):
                                                            a('<!-- EVENT TITLE -->')
                                                            with a.div(style='font-family:Helvetica;font-size:17px;font-weight:bold;line-height:1;text-align:left;color:black;'):
                                                                a('There Is An Imposter (Syndrome) Among Us')
                                                    with a.tr():
                                                        with a.td(align='left', style='font-size:0px;padding:9px 25px;word-break:break-word;'):
                                                            a('<!-- EVENT DESCRIPTION -->')
                                                            with a.div(style='font-family:Ubuntu, Helvetica, Arial, sans-serif;font-size:13px;line-height:1;text-align:left;color:#525252;'):
                                                                a("So many of us have been there. Feeling like the only one who doesn't belong. The only one who doesn't deserve it. How does one live with Imposter Syndrome?")
                                                    with a.tr():
                                                        with a.td(align='center', style='font-size:0px;padding:10px 25px;word-break:break-word;', **{'vertical-align': 'middle'}):
                                                            with a.table(align='center', border='0', cellpadding='0', cellspacing='0', role='presentation', style='border-collapse:separate;width:100%;line-height:100%;'):
                                                                with a.tr():
                                                                    with a.td(align='center', bgcolor='#1051ea', role='presentation', style='border:none;border-radius:3px;cursor:auto;padding:4px 25px;background:#1051ea;color:#ffffff;font-family:Ubuntu, Helvetica, Arial, sans-serif;font-size:13px;font-weight:normal;Margin:0;text-decoration:none;text-transform:none;', valign='middle'):
                                                                        a('<!-- EVENT LINK -->')
                                                                        with a.a(href='https://media.csesoc.org.au/there-is-an-imposter-syndrome-among-us/', style='text-decoration:none;', target='_blank'):
                                                                            with a.p(style='background:#1051ea;color:#ffffff;font-family:Ubuntu, Helvetica, Arial, sans-serif;font-size:13px;font-weight:normal;line-height:200%;Margin:0;text-decoration:none;text-transform:none;', target='_blank'):
                                                                                a('<!-- EVENT BUTTON TEXT -->')
                                                                                a('READ ARTICLE')
                        a('<!-- xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx   END EVENT  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx-->')
                        a('<!-- xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  START Event xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx-->')
                        with a.div(style='background:#ffffff;background-color:#ffffff;Margin:0px auto;max-width:600px;'):
                            with a.table(align='center', border='0', cellpadding='0', cellspacing='0', role='presentation', style='background:#ffffff;background-color:#ffffff;width:100%;'):
                                with a.tbody():
                                    with a.tr():
                                        with a.td(style='direction:ltr;font-size:0px;padding:5px 0;text-align:center;vertical-align:top;'):
                                            a.p(style='border-top:dashed 1px lightgrey;font-size:1;margin:0px auto;width:100%;padding-bottom:15px;')
                                            a('<!-- Left image -->')
                                            with a.div(klass='mj-column-per-50 outlook-group-fix', style='font-size:13px;text-align:left;direction:ltr;display:inline-block;vertical-align:top;width:50%;'):
                                                with a.table(border='0', cellpadding='0', cellspacing='0', role='presentation', style='vertical-align:top;', width='100%'):
                                                    with a.tr():
                                                        with a.td(align='left', style='font-size:0px;padding:10px;word-break:break-word;'):
                                                            with a.table(align='left', border='0', cellpadding='0', cellspacing='0', role='presentation', style='border-collapse:collapse;border-spacing:0px;'):
                                                                with a.tbody():
                                                                    with a.tr():
                                                                        a('<!-- EVENT IMAGE -->')
                                                                        with a.td(style='width:280px;'):
                                                                            a.img(height='auto', src='https://media.csesoc.org.au/content/images/size/w600/2021/11/Post-grad-guide-post--Facebook-Cover-.jpg', style='border:0;display:inline-block;outline:none;text-decoration:none;height:auto;width:100%;', width='280')
                                            a('<!-- right paragraph -->')
                                            with a.div(klass='mj-column-per-50 outlook-group-fix', style='font-size:13px;text-align:left;direction:ltr;display:inline-block;vertical-align:top;width:50%;'):
                                                with a.table(border='0', cellpadding='0', cellspacing='0', role='presentation', style='vertical-align:top;', width='100%'):
                                                    with a.tr():
                                                        with a.td(align='left', style='font-size:0px;padding:9px 25px;word-break:break-word;'):
                                                            a('<!-- EVENT TITLE -->')
                                                            with a.div(style='font-family:Helvetica;font-size:17px;font-weight:bold;line-height:1;text-align:left;color:black;'):
                                                                a('Postgraduate Guide')
                                                    with a.tr():
                                                        with a.td(align='left', style='font-size:0px;padding:9px 25px;word-break:break-word;'):
                                                            a('<!-- EVENT DESCRIPTION -->')
                                                            with a.div(style='font-family:Ubuntu, Helvetica, Arial, sans-serif;font-size:13px;line-height:1;text-align:left;color:#525252;'):
                                                                a('An all encompassing guide for post graduate students at UNSW!')
                                                    with a.tr():
                                                        with a.td(align='center', style='font-size:0px;padding:10px 25px;word-break:break-word;', **{'vertical-align': 'middle'}):
                                                            with a.table(align='center', border='0', cellpadding='0', cellspacing='0', role='presentation', style='border-collapse:separate;width:100%;line-height:100%;'):
                                                                with a.tr():
                                                                    with a.td(align='center', bgcolor='#1051ea', role='presentation', style='border:none;border-radius:3px;cursor:auto;padding:4px 25px;background:#1051ea;color:#ffffff;font-family:Ubuntu, Helvetica, Arial, sans-serif;font-size:13px;font-weight:normal;Margin:0;text-decoration:none;text-transform:none;', valign='middle'):
                                                                        a('<!-- EVENT LINK -->')
                                                                        with a.a(href='https://media.csesoc.org.au/postgraduate-guide/', style='text-decoration:none;', target='_blank'):
                                                                            with a.p(style='background:#1051ea;color:#ffffff;font-family:Ubuntu, Helvetica, Arial, sans-serif;font-size:13px;font-weight:normal;line-height:200%;Margin:0;text-decoration:none;text-transform:none;', target='_blank'):
                                                                                a('<!-- EVENT BUTTON TEXT -->')
                                                                                a('READ ARTICLE')
                        a('<!-- Events 2 -->')
                        a('<!-- xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx   END EVENT  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx-->')
                        a('<!-- START Job Opportunities Header Image Section ------>')
                        a.div(style='background-color:white;Margin:0px auto;max-width:600px;height:10px;')
                        with a.div(klass='height-fix', style='background:url(https://i.imgur.com/twzB46W.jpeg) top center / contain no-repeat;Margin:0px auto;max-width:600px;height:127px;'):
                            with a.div(style='line-height:0;font-size:0;'):
                                with a.table(align='center', border='0', cellpadding='0', cellspacing='0', role='presentation', style='background:top center / contain no-repeat;width:100%;'):
                                    with a.tbody():
                                        with a.tr():
                                            a.td(style='direction:ltr;font-size:0px;padding:20px 0;text-align:center;vertical-align:top;')
                        a('<!-- END Job Opportunities Header Image Section ------>')
                        a('<!-- xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  INDIVIDUAL JOB START xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx-->')
                        with a.div(style='background:white;background-color:white;Margin:0px auto;max-width:600px;'):
                            with a.div(style='padding:20px;max-width:600px;'):
                                with a.table(align='center', border='0', cellpadding='0', cellspacing='0', role='presentation', style='margin: 0px auto; min-width: 100%;', width='100%'):
                                    with a.tbody():
                                        with a.tr():
                                            with a.td(align='center', bgcolor='#1051ea', style='background-color: #1051ea;', valign='top'):
                                                with a.table(align='center', border='0', cellpadding='0', cellspacing='0', role='presentation', style='min-width: 100%; margin: 0px auto;mso-table-lspace:0pt; mso-table-rspace:0pt;', width='5'):
                                                    with a.tbody():
                                                        with a.tr():
                                                            a.td(height='1', style='height: 1px; font-size: 0px; line-height: 0;', valign='top', **{'aria-hidden': 'true'})
                                            with a.td(align='center', valign='top'):
                                                with a.table(align='left', border='0', cellpadding='0', cellspacing='0', role='presentation', style='min-width:100%; max-width:100%;mso-table-lspace:0pt; mso-table-rspace:0pt;', width='20'):
                                                    with a.tbody():
                                                        with a.tr():
                                                            a.td(align='center', height='20', style='height: 20px; font-size: 0px; line-height: 0;', valign='top', **{'aria-hidden': 'true'})
                                            with a.td(align='center', valign='top'):
                                                with a.table(align='center', border='0', cellpadding='0', cellspacing='0', role='presentation', style='margin: 0px auto; min-width: 100%;', width='100%'):
                                                    with a.tbody():
                                                        with a.tr():
                                                            with a.td(align='center', valign='top'):
                                                                with a.table(align='center', border='0', cellpadding='0', cellspacing='0', role='presentation', style='margin: 0px auto; min-width: 100%;', width='100%'):
                                                                    with a.tbody():
                                                                        with a.tr():
                                                                            with a.td(align='left', style="font-size: 18px; color: #333333; font-weight: bold; font-family: 'Open Sans', Arial, Helvetica, sans-serif; word-break: break-word; line-height: 1;"):
                                                                                with a.span(style="color: #333333; font-style: normal; text-align: left; line-height: 24px; font-size: 18px; font-weight: 700; font-family: 'Open Sans', Arial, Helvetica, sans-serif;"):
                                                                                    with a.strong(style="font-size: 18px; font-weight: 700; font-family: 'Open Sans', Arial, Helvetica, sans-serif;"):
                                                                                        a('<!-- Job Title (leave the " - ") ------>')
                                                                                        a('Enactus UNSW - CircEx -')
                                                                                        with a.span(style="text-decoration: underline; color: #333333; font-style: normal; text-align: left; line-height: 24px; font-size: 18px; font-weight: 700; font-family: 'Open Sans', Arial, Helvetica, sans-serif;"):
                                                                                            with a.span(style="font-style: normal; text-align: left; color: #333333; line-height: 24px; font-size: 18px; font-weight: 700; font-family: 'Open Sans', Arial, Helvetica, sans-serif;"):
                                                                                                a("<!-- Job LINK and link title, e.g. 'open now'------>")
                                                                                                with a.a(href='https://docs.google.com/forms/d/e/1FAIpQLSdxSM9EQ6ZUTTawCzzfCl4Mze-4nhMsdS0kjXgyZpfcMhAM5Q/viewform', style='color:black;', target='_blank'):
                                                                                                    a('Apply Now')
                                                                        a('<!-- start space -->')
                                                                        with a.tr():
                                                                            a.td(height='7', style='height: 7px; font-size: 0px; line-height: 0;', valign='top', **{'aria-hidden': 'true'})
                                                                        a('<!-- end space -->')
                                                                        with a.tr():
                                                                            with a.td(align='left', style="font-size: 14px; color: #888888; font-weight: normal; font-family: 'Open Sans', Arial, Helvetica, sans-serif; word-break: break-word; line-height: 1;"):
                                                                                with a.span(style="font-style: normal; text-align: left; color: #888888; line-height: 24px; font-size: 14px; font-weight: 400; font-family: 'Open Sans', Arial, Helvetica, sans-serif;"):
                                                                                    a('<!-- Job description, add <br> new lines as needed ------>')
                                                                                    a('The student-led team at CircEx is looking for backend and React developers to help us during the two-week Industrial-Training and AHEGS-accredited Social Impact Traineeship (SIT).')
                                                                                    a.br()
                                                                                    a.br()
                                                                                    a("CircEx is a new project at Enactus UNSW, where the team is building a chrome extension concept to digitalize second-hand shopping and reduce society's environmental footprint. When a user goes onto eBay or Amazon, the chrome extension would run a reverse image search on a charity op-shop database, finding second-hand alternatives for the items on the eCommerce site.")
                                                                                    a.br()
                                                                                    a.br()
                                                                                    a('For software engineering students,')
                                                                                    a.b(_t='CircEx is also approved to be used for your Industrial Training.')
                                                                                    a.br()
                                                                                    a.br()
                                                                                    a('For more details, check out')
                                                                                    with a.a(href='https://drive.google.com/file/d/1QgAbji1JbD3I1wVfCdm4cUDk-3IzJG4i/view', style='color:blue;', target='_blank'):
                                                                                        a("CircEx's concept video")
                                                                                    a('.')
                                                                                    a.br()
                                                                                    a.br()
                                                                                    a('Registrations close Saturday Jan 8 11:59PM')
                                                                        a('<!-- start space -->')
                                                                        with a.tr():
                                                                            a.td(height='12', style='height: 12px; font-size: 0px; line-height: 0;', valign='top', **{'aria-hidden': 'true'})
                                                                        a('<!-- end space -->')
                        a('<!-- xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  INDIVIDUAL JOB END xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx-->')
                        a('<!-- Sponsors Section ------->')
                        with a.div(klass='height-fix-sponsor', style='background:url(https://i.imgur.com/XvCLqIg.png) bottom center / contain no-repeat;Margin:0px auto;max-width:600px;height:315px;'):
                            with a.div(style='line-height:0;font-size:0;'):
                                with a.table(align='center', border='0', cellpadding='0', cellspacing='0', role='presentation', style='background:top center / contain no-repeat;width:100%;'):
                                    with a.tbody():
                                        with a.tr():
                                            a.td(style='direction:ltr;font-size:0px;padding: 0px 0;text-align:center;vertical-align:top;')
                        a('<!-- END Sponsors Section ------->')
                        a('<!-- START Social footer ------->')
                        with a.div(style='background:#3c54ec;background-color:#3c54ec;Margin:0px auto;max-width:600px;'):
                            with a.table(align='center', border='0', cellpadding='0', cellspacing='0', role='presentation', style='background:#3c54ec;background-color:#3c54ec;width:100%;'):
                                with a.tbody():
                                    with a.tr():
                                        with a.td(style='direction:ltr;font-size:0px;padding:20px 0;text-align:center;vertical-align:top;'):
                                            with a.div(style='font-family:Ubuntu, Helvetica, Arial, sans-serif;font-size:13px;line-height:1;text-align:center;color:white;text-decoration:none!important;'):
                                                a('2021 Sponsors')
                        a('<!-- END Social footer ------->')
                        a('<!-- START Shadow ------------>')
                        with a.div(style='background:#f0f0f0 url(https://www.csesoc.unsw.edu.au/static/media/announce/static/newsletter_shadow.png) top center / cover no-repeat;Margin:0px auto;max-width:600px;height:30px;'):
                            with a.div(style='line-height:0;font-size:0;height:30px;'):
                                with a.table(align='center', background='https://www.csesoc.unsw.edu.au/static/media/announce/static/newsletter_shadow.png', border='0', cellpadding='0', cellspacing='0', role='presentation', style='background:#f0f0f0 url(https://www.csesoc.unsw.edu.au/static/media/announce/static/newsletter_shadow.png) top center / contain no-repeat;width:100%;height:30px;'):
                                    with a.tbody():
                                        with a.tr():
                                            a.td(style='direction:ltr;font-size:0px;padding:20px 0;text-align:center;vertical-align:top;height:30px;')
                        a('<!-- END Shadow ------------>')
                        a('<!-- START Footer ---------->')
                        with a.div(style='background:#f0f0f0;background-color:#f0f0f0;Margin:0px auto;max-width:600px;'):
                            with a.table(align='center', border='0', cellpadding='0', cellspacing='0', role='presentation', style='background:#f0f0f0;background-color:#f0f0f0;width:100%;'):
                                with a.tbody():
                                    with a.tr():
                                        with a.td(style='direction:ltr;font-size:0px;padding:20px 0;text-align:center;vertical-align:top;'):
                                            with a.div(style='font-family:Ubuntu, Helvetica, Arial, sans-serif;font-size:13px;line-height:3;text-align:center;color:#888888;'):
                                                a.a(href='https://www.facebook.com/csesoc', style='color:#888888;', _t='Facebook Page')
                                                a('|')
                                                a.a(href='https://www.facebook.com/groups/csesoc/', style='color:#888888;', _t='Facebook Group')
                                                a('|')
                                                a.a(href='https://www.linkedin.com/company/csesoc/about/', style='color:#888888;', _t='LinkedIn')
                                            with a.div(style='font-family:Ubuntu, Helvetica, Arial, sans-serif;font-size:13px;line-height:3;text-align:center;color:#888888;'):
                                                a('Contact:')
                                                a.b(_t='csesoc@csesoc.org.au')
                                            with a.div(style='font-family:Ubuntu, Helvetica, Arial, sans-serif;font-size:13px;line-height:3;text-align:center;color:#888888;'):
                                                a('If you do not wish to receive our newsletters,')
                                                with a.a(href='https://status.cse.unsw.edu.au/Control_Panel/Mail/Mailing_List_Subscriptions/', style='color:#888888;', target='_blank'):
                                                    a.b(_t='unsubscribe here')
                                                a('.')
                        a('<!-- END Footer ---------->')

